### ISSUE TITLE
merging upstream into ags branch is a mess

### ISSUE THREAD

**Issue by rofl0r** [adventuregamestudio/scummvm#1]
https://github.com/adventuregamestudio/scummvm/commit/3b81558909211d5ce8fd92528fd2d63598f50403

@morganwillcock followed in fuzzy's steps who to my great dismay used the messy branch-merging approach, rather than rebasing the ags branch onto upstream master, which would keep a clean linear commit history of the branch.

however the guys from scummvm ("digitall") requested exactly the latter, namely a clean rebase: http://forums.scummvm.org/viewtopic.php?t=14463&postdays=0&postorder=asc&start=30 . so it seems this needs to be done anyway, so it would be better to do it sooner than later.

**Comment by morganwillcock** [comment]
It wasn't mentioned until I'd already done the merge. I'll probably need a practice go at a rebase, but it is on the to-do list. I've only just got to the point where something in ScummVM needs a change, so now is probably a good time. Feel free to point me in the direction of some good instructions...

**Comment by rofl0r** [comment]
i made some comments about the approach i usually use on the ags repo on the issue that mentions this scummvm port. let me know if you can't find it, so i'll dig through the issues i commented on...

**Comment by ghost** [comment]
> i made some comments about the approach i usually use on the ags repo on the issue that mentions this scummvm port. let me know if you can't find it, so i'll dig through the issues i commented on...

I think this one: https://github.com/adventuregamestudio/ags/issues/290#issuecomment-364665356


Regarding the issue, at first I thought that there was only one merge with master done by fuzzie as one of her last commits, but unfortunately it's not, for example here are other ones made much earlier in the middle of "ags" branch:
9d45e13a772d11237b4b5c3046030023c118f308
fb2414ff5e31f78337edbd01b7c194b3767dc208
and there are more.

Personally, I'd probably create a new branch on top of current scummvm's "master" (or rename "ags" into something and create new "ags"), and either try cherry-picking old meaningful commits in an order, or create patches from these and apply in bulk. Idk if there is an even better way.

**Comment by rofl0r** [comment]
> I think this one

indeed, thanks

> Personally, I'd probably create a new branch on top of current scummvm's "master" (or rename "ags" into something and create new "ags"), and either try cherry-picking old meaningful commits in an order

yes, that could work

> or create patches from these and apply in bulk

not sure what you mean with applying in bulk, but usually the patches can't all be applied automatically, since some parts of the original codebase changed.

however, in this specific situation, almost all changes are contained in an ags-specific directory, so only a few commits which wired the ags engine into the scummvm guts could be problematic. that means that cherry-picking the commit should indeed work for the vast majority of commits, and for those that don't, making a patch, and applying the hunks that merge automatically and the rest by hand seems to be best option imo.

**Comment by csnover** [comment]
Try just using an [interactive rebase](https://git-scm.com/book/id/v2/Git-Tools-Rewriting-History), `git rebase -i`. It is “like” cherry picking, but you get the entire list of commits at once in an editor so you can control which ones to remove, rearrange them, squash/fixup commits together, stop at specific commits to edit them manually, etc. The most important thing with a rebase is to make sure all the commits are fixed up so that they continue to compile, in order that bisection can be done later on. In this case that would mean at least moving the fixes for e.g. `initGraphics` API changes up to the top of the commit list so they are applied to the entire history.

**Comment by rofl0r** [comment]
interactive rebase is incredibly powerful, *BUT* it does a lot of stuff behind one's back like silently removing merge commits. i use it generally to move order of commits, to remove or reword commits, or to squash commits together. none of those features are helpful in this scenario, and i fear they will even be counter-productive. especially when you're new to it, you can horribly mess up your work if you dont have backups...
so i don't see how it can help here.

**Comment by morganwillcock** [comment]
If attempting it, should I be adding the real scummvm master as a remote and then use "rebase --onto" from the ags branch, so the master branch here is never touched? Or would there be a benefit to rebasing the master?

**Comment by ghost** [comment]
> If attempting it, should I be adding the real scummvm master as a remote and then use "rebase --onto" from the ags branch, so the master branch here is never touched? Or would there be a benefit to rebasing the master?

We should not be **rebasing** our master, the master branch in our fork should be naturally synced (merged without commit) with the scummvm master.

I.e.: first sync our master with theirs, then rebase "ags" on our fork's master.

**Comment by csnover** [comment]
> it does a lot of stuff behind one's back like silently removing merge commits

Getting rid of the merge commits pulling master into ags branch is the intent of doing the rebase.

> you can horribly mess up your work if you dont have backups...

I agree that git’s learning curve is more of a cliff, and, I’ve done a lot of rebasing and I have never encountered a situation where it messes anything up permanently, so I am pretty sure this is just a common misconception.

If you get in an unrecoverable situation during a rebase, you can just run `git rebase --abort` to roll the whole thing back. If you only notice something is messed up after the rebase is finished, `git reflog` will show you the whole history of git changes so you can find the previous branch state and just reset back to it with `git reset --merge <commit id>`. I’m pretty sure you can also roll back to just a previous step of the rebase, though I’ve never had occasion to do this so I can’t say offhand what the right way to do it is.

> If attempting it, should I be adding the real scummvm master as a remote and then use "rebase --onto" from the ags branch, so the master branch here is never touched? Or would there be a benefit to rebasing the master?

Essentially all you do for an interactive rebase vs a merge is replace `git merge` with `git rebase -i`. So, assuming your upstream scummvm remote is named `upstream`, the full list of steps are (1) check out the `ags` branch (you probably have already) with `git checkout ags`, (2) `git pull` to make sure you’re up-to-date with upstream, (3) run `git rebase -i upstream/master`. Git will walk you through the rest of the process. If the rebase stops in the middle and you are unsure what to do next, `git status` will usually tell you what you need to do. Once you’re done, your `ags` branch will be rebased onto `upstream/master`, which means that it will be as-if you just started working on the branch from today.

**Comment by morganwillcock** [comment]
@csnover thank you for the guide (and thank you for the chat about audiostreams).
I'll try to give this a test run over the weekend.

**Comment by morganwillcock** [comment]
I've given it a few practise runs, but moving the build fixes to the start of the commit list generates some pretty large changes when trying to resolve merge conflicts. I think it is possible to just step through every commit, running make after each step to check that it builds, as there are only ~370 commits to go through (and I think only 3 of these have fixes for upstream changes). The only issue I've found which would stop this approach is going backwards in the rebase, I've only found [this method](https://stackoverflow.com/questions/44058756/git-what-to-do-if-accidentally-skipped-while-rebasing) so far, as `reset --merge` doesn't affect the rebase state. Does anyone know of any way to return to the previous rebase action?

**Comment by ivan-mogilko** [comment]
Maybe use cherry picks instead of rebase? Since you have to test build after each commit anyway. With cherrypicks you are doing single-step operation only.

**Comment by csnover** [comment]
One thing that I try to do in cases like this is to rebase in two phases. First I will run the initial rebase without interaction so that it just reapplies all commits. In this case, this results in only one merge conflict on the initial commit, which is resolved by keeping all the HEAD changes and manually adding in the `engines/ags/configure.engine` file which was added in a future commit. This results in a branch with no merges, which builds at the head, but has broken commits in the history. Then the second phase is to look at the commits which don’t build successfully and fix them, as you’ve suggested. This can be done in an automated manner by doing this:

1. Run `git rebase -i origin/master` to start an interactive rebase
2. Change every `pick` to `edit`, save and exit the editor
3. Run `while make -j6 && git rebase --continue; do :; done`. This will build every commit and continue the rebase until there is a compilation failure (replace `-j6` with the number of threads you want to use to build)
4. Fix the compilation errors, run `git add` and `git commit --amend` to fix the commit, and repeat from step 3 until the rebase is all done

As far as reverting to a previous rebase step, [these instructions](http://www.arigrant.com/blog/2014/5/4/git-rebase-stepping-forward-and-back) should give you what you want, though I haven’t tested them myself.

**Comment by morganwillcock** [comment]
Should be done. I don't think it can get any cleaner (the seventh time's the charm) and it compiles on every commit.

**Comment by rofl0r** [comment]
congrats! did you push it to a new branch ?

**Comment by ghost** [comment]
Looks great actually, I tried comparing with old fuzzie's branch in her repository, and difference seem to be equal to the changes that you've added recently, so it *might* be correct.

One question that I have, now when "ags" branch is rebased. I was thinking that maybe it was a mistake to fork from from fuzzie and not directly from scummvm repository, because it will probably be the latter where we are going to do pull request to. Is there a way to change "forked from" repository address on github, and if yes, should we do that?

**Comment by morganwillcock** [comment]
I don't think you can change it without recreating the repository. I had assumed at some point it would permanently move to scummvm, so there wouldn't be regular changes going back and forth.

**Comment by rofl0r** [comment]
i think this can be closed.  @morganwillcock has done a pretty good job, although i would've wished that the old ags had been preserved, and a new branch created. also there are a couple commits that lack `AGS:` in the commit message, but this can easily fixed with interactive rebase and the reword option.
anyway, congrats!

**Comment by ghost** [comment]
> i would've wished that the old ags had been preserved, and a new branch created

We could push old branch into this repository again, under different name (ags-old?), if necessary?
Or rename "ags" into "ags-new" and restore old branch under original name.
I'd presume there are not many people who cloned this repository yet, so such action should not cause much issue.

**Comment by morganwillcock** [comment]
Yes, that may be useful. Any fixes I made will have been part of the rebase, so it would really only be missing the changes where I started enabling scripting functions (this is probably a bonus, so someone can see where I have misinterpreted the original approach or scummvm internals).
